In [1]:
import sys
!{sys.executable} -m pip install pandas numpy

Requirement already satisfied: pandas in ./venv/lib/python3.12/site-packages (3.0.5)
Requirement already satisfied: numpy in ./venv/lib/python3.12/site-packages (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_colwidth', None)

d = pd.read_json("cleaned_products.json")
d.head()

,title,url,price_eur,dna_price_eur,customer_price_eur,in_stock,manufacturer,gift
0,"Valco VMK25.2 vastamelukuulokkeet, Musta",https://kauppa.dna.fi/tuote/p/valco-vmk25-2-vastamelukuulokkeet-musta,199.00,199.00,199.00,True,Valco,Kaupan päälle jopa 29 € arvoinen suojakuori!
1,"Google Pixel 11 5G, 256 Gt, Frost",https://kauppa.dna.fi/tuote/p/google-pixel-11-5g-256-gt-frost,10.49,10.49,10.49,True,Google,Kaupan päälle jopa 519 € arvoinen Jopo!
2,"Google Pixel 11 Pro 5G, 256 Gt, Canyon",https://kauppa.dna.fi/tuote/p/google-pixel-11-pro-5g-256-gt-canyon,12.59,12.59,12.59,True,Google,Kaupan päälle jopa 519 € arvoinen Jopo!
3,"Google Pixel 11 Pro Fold 5G, 256 Gt, Obsidian",https://kauppa.dna.fi/tuote/p/google-pixel-11-pro-fold-5g-256-gt-obsidian,20.89,20.89,20.89,True,Google,Kaupan päälle jopa 519 € arvoinen Jopo!
4,"Google Pixel 11 Pro XL 5G, 256 Gt, Canyon",https://kauppa.dna.fi/tuote/p/google-pixel-11-pro-xl-5g-256-gt-canyon,14.69,14.69,14.69,True,Google,Kaupan päälle jopa 519 € arvoinen Jopo!

In [2]:
df = pd.DataFrame(d)
df

,title,url,price_eur,dna_price_eur,customer_price_eur,in_stock,manufacturer,gift
0,"Valco VMK25.2 vastamelukuulokkeet, Musta",https://kauppa.dna.fi/tuote/p/valco-vmk25-2-vastamelukuulokkeet-musta,199.00,199.00,199.00,True,Valco,Kaupan päälle jopa 29 € arvoinen suojakuori!
1,"Google Pixel 11 5G, 256 Gt, Frost",https://kauppa.dna.fi/tuote/p/google-pixel-11-5g-256-gt-frost,10.49,10.49,10.49,True,Google,Kaupan päälle jopa 519 € arvoinen Jopo!
2,"Google Pixel 11 Pro 5G, 256 Gt, Canyon",https://kauppa.dna.fi/tuote/p/google-pixel-11-pro-5g-256-gt-canyon,12.59,12.59,12.59,True,Google,Kaupan päälle jopa 519 € arvoinen Jopo!
3,"Google Pixel 11 Pro Fold 5G, 256 Gt, Obsidian",https://kauppa.dna.fi/tuote/p/google-pixel-11-pro-fold-5g-256-gt-obsidian,20.89,20.89,20.89,True,Google,Kaupan päälle jopa 519 € arvoinen Jopo!
4,"Google Pixel 11 Pro XL 5G, 256 Gt, Canyon",https://kauppa.dna.fi/tuote/p/google-pixel-11-pro-xl-5g-256-gt-canyon,14.69,14.69,14.69,True,Google,Kaupan päälle jopa 519 € arvoinen Jopo!
...,...,...,...,...,...,...,...,...
305,"JBL Live Flex langattomat vastamelunappikuulokkeet, Musta",https://kauppa.dna.fi/tuote/p/jbl-live-flex-langattomat-vastamelunappikuulokkeet-musta,39.00,39.00,79.00,False,JBL,No gift
306,"JBL Wave Flex langattomat kuulokkeet, Beige",https://kauppa.dna.fi/tuote/p/jbl-wave-flex-langattomat-kuulokkeet-beige,9.00,9.00,19.00,False,JBL,No gift
307,EZVIZ BC1-B2 -valvontakamerapaketti,https://kauppa.dna.fi/tuote/p/ezviz-bc1-b2-valvontakamerapaketti,99.00,99.00,229.00,True,EZVIZ,No gift
308,"JBL Live Pro 2 langattomat vastamelunappikuulokkeet, Musta",https://kauppa.dna.fi/tuote/p/jbl-live-pro-2-langattomat-vastamelunappikuulokkeet-musta,39.00,39.00,79.00,False,JBL,No gift
309,"JBL Tune Flex langattomat vastamelunappikuulokkeet, Valkoinen",https://kauppa.dna.fi/tuote/p/jbl-tune-flex-langattomat-vastamelunappikuulokkeet-valkoinen,29.00,29.00,49.00,True,JBL,No gift

In [3]:
df[df["manufacturer"] == "Samsung"]

,title,url,price_eur,dna_price_eur,customer_price_eur,in_stock,manufacturer,gift
8,"Samsung Galaxy A27 5G, 256 Gt, Musta",https://kauppa.dna.fi/tuote/p/samsung-galaxy-a27-5g-256-gt-musta,449.0,449.0,449.0,True,Samsung,Kaupan päälle jopa 55 € arvoinen näytönsuoja!
9,"Samsung Galaxy A27 5G, 128 Gt, Musta",https://kauppa.dna.fi/tuote/p/samsung-galaxy-a27-5g-128-gt-musta,329.0,349.0,349.0,True,Samsung,Kaupan päälle jopa 55 € arvoinen näytönsuoja!
10,"Samsung Galaxy Watch Ultra2 -älykello, Harmaa",https://kauppa.dna.fi/tuote/p/samsung-galaxy-watch-ultra2-alykello-harmaa,749.0,749.0,749.0,True,Samsung,No gift
11,"Samsung Galaxy Watch9 eSIM -älykello, 40 mm, Hopea",https://kauppa.dna.fi/tuote/p/samsung-galaxy-watch9-esim-alykello-40-mm-hopea,459.0,459.0,459.0,True,Samsung,No gift
12,"Samsung Galaxy Watch9 eSIM -älykello, 44 mm, Hopea",https://kauppa.dna.fi/tuote/p/samsung-galaxy-watch9-esim-alykello-44-mm-hopea,489.0,489.0,489.0,True,Samsung,No gift
...,...,...,...,...,...,...,...,...
264,"Samsung Galaxy A16, Black",https://kauppa.dna.fi/tuote/p/samsung-galaxy-a16-black,119.0,119.0,119.0,True,Samsung,Kaupan päälle jopa 55 € arvoinen näytönsuoja!
272,"Samsung Galaxy Fit3 -aktiivisuusranneke, Harmaa",https://kauppa.dna.fi/tuote/p/samsung-galaxy-fit3-aktiivisuusranneke-harmaa,29.0,29.0,65.0,False,Samsung,No gift
282,"Samsung Galaxy Watch Ultra, Titanium White",https://kauppa.dna.fi/tuote/p/samsung-galaxy-watch-ultra-white,549.0,549.0,699.0,True,Samsung,No gift
283,"Samsung Galaxy Buds3 langattomat kuulokkeet, Hopea",https://kauppa.dna.fi/tuote/p/samsung-galaxy-buds3-langattomat-vastamelukuulokkeet-hopea,79.0,79.0,179.0,False,Samsung,No gift
284,"Samsung Galaxy Watch7 4G, 40 mm, Green",https://kauppa.dna.fi/tuote/p/samsung-galaxy-watch7-4g-40-mm-green,199.0,199.0,249.0,False,Samsung,No gift

In [5]:
s26_ultra_df = df[df["title"].str.contains("S26 Ultra", case=False, na=False)]
s26_ultra_df

,title,url,price_eur,dna_price_eur,customer_price_eur,in_stock,manufacturer,gift
98,"Samsung Galaxy S26 Ultra 5G, 1 Tt, Black",https://kauppa.dna.fi/tuote/p/samsung-galaxy-s26-ultra-5g-1-tt-black,14.99,14.99,14.99,True,Samsung,Kaupan päälle jopa 399 € arvoinen tabletti!
99,"Samsung Galaxy S26 Ultra 5G, 256 Gt, Black",https://kauppa.dna.fi/tuote/p/samsung-galaxy-s26-ultra-5g-256-gt-black,12.99,12.99,12.99,True,Samsung,Kaupan päälle jopa 399 € arvoinen tabletti!
100,"Samsung Galaxy S26 Ultra 5G, 512 Gt, Black",https://kauppa.dna.fi/tuote/p/samsung-galaxy-s26-ultra-5g-512-gt-black,13.99,13.99,13.99,True,Samsung,Kaupan päälle jopa 399 € arvoinen tabletti!